version: '3'
services:
  api:
    build: ./api
    ports:
      - "5001:5000"
    networks:
      - my_network

  web:
    build: ./web
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
